//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZdravoKlinika.Resources.Localisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZdravoKlinika.Resources.Localisation.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додај.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Алергени.
        /// </summary>
        internal static string alergies {
            get {
                return ResourceManager.GetString("alergies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количина.
        /// </summary>
        internal static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анамнеза.
        /// </summary>
        internal static string anamnesis {
            get {
                return ResourceManager.GetString("anamnesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Особљле је пријатно, професионално и увек на услузи..
        /// </summary>
        internal static string appFeedbackQ1 {
            get {
                return ResourceManager.GetString("appFeedbackQ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просторије за преглед су чисте и опремљене..
        /// </summary>
        internal static string appFeedbackQ2 {
            get {
                return ResourceManager.GetString("appFeedbackQ2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чекаонице су пријатне и простране..
        /// </summary>
        internal static string appFeedbackQ3 {
            get {
                return ResourceManager.GetString("appFeedbackQ3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Музика у чекаоницама је пријатна и умирујућа..
        /// </summary>
        internal static string appFeedbackQ4 {
            get {
                return ResourceManager.GetString("appFeedbackQ4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Боравак у просторијама и коришћење услуга Здраво корпорације је на мене оставило позитиван утицај..
        /// </summary>
        internal static string appFeedbackQ5 {
            get {
                return ResourceManager.GetString("appFeedbackQ5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У будућности ћу се поново определити за услуге Здраво корпорације..
        /// </summary>
        internal static string appFeedbackQ6 {
            get {
                return ResourceManager.GetString("appFeedbackQ6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Апликација Здраво корпорације је адекватна..
        /// </summary>
        internal static string appFeedbackQ7 {
            get {
                return ResourceManager.GetString("appFeedbackQ7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лекар је био љубазан..
        /// </summary>
        internal static string appointmentQ1 {
            get {
                return ResourceManager.GetString("appointmentQ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лекар је био професионалан..
        /// </summary>
        internal static string appointmentQ2 {
            get {
                return ResourceManager.GetString("appointmentQ2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лекар ми је помогао са мојим проблемом..
        /// </summary>
        internal static string appointmentQ3 {
            get {
                return ResourceManager.GetString("appointmentQ3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ординација је била адекватно опремљена..
        /// </summary>
        internal static string appointmentQ4 {
            get {
                return ResourceManager.GetString("appointmentQ4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хигијена просторије и опрема је задовољавајућа..
        /// </summary>
        internal static string appointmentQ5 {
            get {
                return ResourceManager.GetString("appointmentQ5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преглед је обављен у заказано време уз минимално чеканје..
        /// </summary>
        internal static string appointmentQ6 {
            get {
                return ResourceManager.GetString("appointmentQ6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задовољан сам услугом лекара..
        /// </summary>
        internal static string appointmentQ7 {
            get {
                return ResourceManager.GetString("appointmentQ7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задовољан сам услугом болнице..
        /// </summary>
        internal static string appointmentQ8 {
            get {
                return ResourceManager.GetString("appointmentQ8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прегледи.
        /// </summary>
        internal static string appointments {
            get {
                return ResourceManager.GetString("appointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип прегледа:.
        /// </summary>
        internal static string appointmentType {
            get {
                return ResourceManager.GetString("appointmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основни подаци.
        /// </summary>
        internal static string basicData {
            get {
                return ResourceManager.GetString("basicData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Крвна група:.
        /// </summary>
        internal static string bloodType {
            get {
                return ResourceManager.GetString("bloodType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коментар.
        /// </summary>
        internal static string comment {
            get {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Датум:.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Датум и време.
        /// </summary>
        internal static string dateAndTime {
            get {
                return ResourceManager.GetString("dateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Датум рођења:.
        /// </summary>
        internal static string dateOfBirth {
            get {
                return ResourceManager.GetString("dateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дијагноза:.
        /// </summary>
        internal static string diagnosis {
            get {
                return ResourceManager.GetString("diagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Белешке лекара:.
        /// </summary>
        internal static string docNotes {
            get {
                return ResourceManager.GetString("docNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доктор:.
        /// </summary>
        internal static string doctor {
            get {
                return ResourceManager.GetString("doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Измени.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Измена термина.
        /// </summary>
        internal static string editAppointment {
            get {
                return ResourceManager.GetString("editAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Измена времена обавештења.
        /// </summary>
        internal static string editNotifTime {
            get {
                return ResourceManager.GetString("editNotifTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адреса е-поште:.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контакт за хитне случајеве:.
        /// </summary>
        internal static string emContact {
            get {
                return ResourceManager.GetString("emContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Број за хитне случајеве:.
        /// </summary>
        internal static string emNumber {
            get {
                return ResourceManager.GetString("emNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваши утисци.
        /// </summary>
        internal static string feedback {
            get {
                return ResourceManager.GetString("feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поље за ваш коментар..
        /// </summary>
        internal static string feedbackField {
            get {
                return ResourceManager.GetString("feedbackField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше мишљење о апликацији можете исказати испод..
        /// </summary>
        internal static string feedbackTitle {
            get {
                return ResourceManager.GetString("feedbackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пол:.
        /// </summary>
        internal static string gender {
            get {
                return ResourceManager.GetString("gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Историја болести.
        /// </summary>
        internal static string history {
            get {
                return ResourceManager.GetString("history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Презиме:.
        /// </summary>
        internal static string lastname {
            get {
                return ResourceManager.GetString("lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одјава.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказивање термина.
        /// </summary>
        internal static string makeAppointment {
            get {
                return ResourceManager.GetString("makeAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Терапије.
        /// </summary>
        internal static string medication {
            get {
                return ResourceManager.GetString("medication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назив лека:.
        /// </summary>
        internal static string medicationName {
            get {
                return ResourceManager.GetString("medicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име:.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Белешка.
        /// </summary>
        internal static string note {
            get {
                return ResourceManager.GetString("note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Белешке.
        /// </summary>
        internal static string notes {
            get {
                return ResourceManager.GetString("notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обавештења.
        /// </summary>
        internal static string notifications {
            get {
                return ResourceManager.GetString("notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Занимање:.
        /// </summary>
        internal static string ocupation {
            get {
                return ResourceManager.GetString("ocupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Број телефона:.
        /// </summary>
        internal static string phoneNumber {
            get {
                return ResourceManager.GetString("phoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приоритет:.
        /// </summary>
        internal static string prio {
            get {
                return ResourceManager.GetString("prio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профил.
        /// </summary>
        internal static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Питање.
        /// </summary>
        internal static string question {
            get {
                return ResourceManager.GetString("question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уклони.
        /// </summary>
        internal static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Соба:.
        /// </summary>
        internal static string room {
            get {
                return ResourceManager.GetString("room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сачувај.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Време:.
        /// </summary>
        internal static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здраво Корпорација.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша белешка:.
        /// </summary>
        internal static string yourNotes {
            get {
                return ResourceManager.GetString("yourNotes", resourceCulture);
            }
        }
    }
}
